### PR TITLE
feat: allow config from dot file in user home

### PR DESCRIPTION
**Pull request by bertbesser**
Hi,

thanks for this neat little tool.

I added support for doing configuration from a dot file in the user home.

Background: The README suggests to create a `config.lua` file in the clone folder, but some installation methods make it impossible to create that file. (E.g. when installing using `builtins.fetchGit` in NixOS you cannot put another file in that folder using your nix config.) Adding a dot file to your home should be possible in any setup.

Thanks,
Bert

### CODE REVIEW

**Comment by novoid** [comment]
I can only speak for Linux/UNIX systems: it's not encouraged to put dotfiles in the `$HOME` any more. For that, most Linux tools are using `$HOME/.config/$TOOL` or `$HOME/.local/share/$TOOL/`.

HTH

**Comment by bertbesser** [comment]
Thanks! Happy to change the implementation if the feature is considered at all :-) 👍

Let's wait for some feedback first.

**Comment by familyfriendlymikey** [comment]
I like the idea and thanks for the PR. Happy to see someone is actually using the config/custom actions!

I agree with novoid, I think the cleanest way would be to put it in `~/.config/mpv-cut/config.lua`.

Also, it's been a while since I read the mpv docs but is `os.getenv` reliable? I think there is `expand-path` for that? I might try this way:

```lua
if pcall(require, "config") then
	mp.msg.info("Loaded config module.")
elseif pcall(require, mp.command_native({"expand-path", "~/.config/mpv-cut/config"})) then
	mp.msg.info("Loaded config from dotfile.")
else
	mp.msg.info("No config loaded.")
end
```

**Comment by bertbesser** [comment]
Hi. I tried your suggested code. I observed that it does not load the file.

I'm not familiar with lua, but could it be that `require` can pick up scripts only from certain paths, called the Lua path? Not sure, though.

I ran into a similar thing when implementing it for the first time, which is why I chose `dofile`, which seems to not have that issue.

**Comment by bertbesser** [comment]
Hi @familyfriendlymikey, I committed the version of the code that works. Note that if I replace `dofile` with `require` in line 121, then the config will not be loaded.

Cheers!

**Comment by familyfriendlymikey** [comment]
Great, thank you :)

**Pull request merged**
